// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  hoare_triple = 2,
  CNAME = 5,
  SIGNED_NUMBER = 28,
  SeqCmd = 76,
  Loop_invariant = 99,
  Invariant = 100,
  OdeNoInv = 104,
  Ode_invariant = 106,
  InvariantWithRule = 107
