// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  hoare_triple = 2,
  CNAME = 3,
  SIGNED_NUMBER = 32,
  SeqCmd = 75,
  Loop_invariant = 98,
  Invariant = 99,
  OdeNoInv = 103,
  Ode_invariant = 105,
  InvariantWithRule = 106
