// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  LineComment = 1,
  hoare_triple = 2,
  CNAME = 7,
  SIGNED_NUMBER = 29,
  SeqCmd = 71,
  Loop_invariant = 93,
  Invariant = 94,
  OdeNoInv = 98,
  Ode_invariant = 100,
  InvariantWithRule = 101
